# Data Setting
DATASET_ROOT_PATH: /data/datasets/
NUM_WORKERS: 8

#IMG Augmentation
IMAGE_ROTATION: 20
IMAGE_FLIP_PROB: 0.5
IMAGE_NUM_CROPS: 64
IMAGE_PAD_CROPS: 4
IMAGE_MEAN: [0.4802, 0.4481, 0.3975]
IMAGE_STD: [0.2302, 0.2265, 0.2262]