WANDB_PROJECT: 'aue8088-pa1'
WANDB_SAVE_DIR: 'wandb/'
WANDB_IMG_LOG_FREQ: 50
WANDB_ENTITY: ${oc.env:WANDB_ENTITY}
WANDB_NAME: ${python:"f'{MODEL_NAME}-B{BATCH_SIZE}-{OPTIMIZER_PARAMS.type}-{SCHEDULER_PARAMS.type}{OPTIMIZER_PARAMS.lr:.1E}'"}
